version: '3'
services:
  frontend1:
    build: ./frontend1
    ports:
      - "8081:80"
  frontend2:
    build: ./frontend2
    ports:
      - "8082:80"
  admin:
    build: ./admin
    ports:
      - "8083:80"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
